### ISSUE TITLE
Issues with pdf-utils append

### ISSUE THREAD

**Issue by ealves-pt** [jsreport/jsreport-weasyprint-pdf#2]
I'm currently trying to generate a pdf that has 4 other templates being appended using the pdf-utils.

This behaviour works fine if I'm using **chrome-pdf** but as soon as I change to **weasyprint-pdf** I get this error:

`Error: Error while executing pdf-utils operations. Invalid value
    at module.exports (/home/ea/jsreport/node_modules/jsreport-core/lib/util/createError.js:10:13)
    at Reporter.createError (/home/ea/jsreport/node_modules/jsreport-core/lib/reporter.js:256:12)
    at AsyncFunction.reporter.afterRenderListeners.insert (/home/ea/jsreport/node_modules/jsreport-pdf-utils/lib/main.js:105:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
caused by: Error: Invalid value
    at Lexer._error (/home/ea/jsreport/node_modules/jsreport-pdfjs/lib/parser/lexer.js:122:11)
    at Object.exports.parse (/home/ea/jsreport/node_modules/jsreport-pdfjs/lib/object/value.js:26:9)
    at Function.parse (/home/ea/jsreport/node_modules/jsreport-pdfjs/lib/object/object.js:68:28)
    at parseObject (/home/ea/jsreport/node_modules/jsreport-pdfjs/lib/object/reference.js:67:20)
    at PDFReference.get [as object] (/home/ea/jsreport/node_modules/jsreport-pdfjs/lib/object/reference.js:13:17)
    at Function.addObjectsRecursive (/home/ea/jsreport/node_modules/jsreport-pdfjs/lib/parser/parser.js:61:35)
    at Function.addObjectsRecursive (/home/ea/jsreport/node_modules/jsreport-pdfjs/lib/parser/parser.js:73:18)
    at Function.addObjectsRecursive (/home/ea/jsreport/node_modules/jsreport-pdfjs/lib/parser/parser.js:68:16)
    at Function.addObjectsRecursive (/home/ea/jsreport/node_modules/jsreport-pdfjs/lib/parser/parser.js:65:16)
    at Function.addObjectsRecursive (/home/ea/jsreport/node_modules/jsreport-pdfjs/lib/parser/parser.js:73:18)`

I've decided to report the issue here but I don't know if it would be better to do so in the pdf-utils repository.

**Comment by ealves-pt** [comment]
Just debugged a little further and it seems that the issue only happens when I try to append more than 1 template.

If I only append one template it works as expected.

I also tried another approach. Instead of append template **B, C, D, E** to template **A** I've tried to do a chain like: **E appends to D**, **D appends to C**, etc... but that fails with the same error.
